create table public.accounts (
    id bigint generated by default as identity primary key,
    household_id bigint not null unique references public.households(id) on delete cascade,
    username text not null unique check (
        username = lower(username) and username ~ '^[a-z0-9._-]{3,50}$'
    ),
    password_hash text not null,
    created_at timestamptz not null default now()
);

create table public.account_sessions (
    id bigint generated by default as identity primary key,
    account_id bigint not null references public.accounts(id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    created_at timestamptz not null default now()
);

create index account_sessions_account_id_idx on public.account_sessions(account_id);
create index account_sessions_expires_at_idx on public.account_sessions(expires_at);

alter table public.accounts enable row level security;
alter table public.account_sessions enable row level security;

create or replace function public.seed_household_categories()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    insert into public.categories (household_id, name, sort_order)
    select new.id, name, sort_order from (values
        ('❓ Uncategorized', 0), ('🏠 Housing', 10), ('🏘️ Rent', 20),
        ('🏡 Mortgage', 30), ('💳 Credit Card', 40), ('💧 Water', 50),
        ('⚡ Electricity', 60), ('🔥 Gas', 70), ('📺 Cable', 80),
        ('🌐 Internet', 90), ('📱 Phone', 100), ('🛒 Groceries', 110),
        ('🍽️ Dining Out', 120), ('🚗 Transportation', 130),
        ('🛡️ Insurance', 140), ('🩺 Healthcare', 150), ('🧸 Childcare', 160),
        ('🎓 Education', 170), ('🎬 Entertainment', 180),
        ('🔁 Subscriptions', 190), ('💰 Savings', 200), ('📉 Debt Payment', 210),
        ('💵 Salary', 220), ('🪙 Other Income', 230), ('📦 Other', 240)
    ) defaults(name, sort_order);
    return new;
end;
$$;

create trigger seed_categories_after_household_insert
after insert on public.households
for each row execute function public.seed_household_categories();

revoke execute on function public.seed_household_categories() from public, anon, authenticated;
