create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    household_id bigint not null references public.households(id) on delete cascade,
    name text not null check (length(btrim(name)) > 0),
    sort_order integer not null default 100,
    created_at timestamptz not null default now(),
    unique (household_id, name)
);

alter table public.categories enable row level security;

insert into public.categories (household_id, name, sort_order)
select h.id, defaults.name, defaults.sort_order
from public.households h
cross join (values
    ('Uncategorized', 0), ('Housing', 10), ('Rent', 20), ('Mortgage', 30),
    ('Credit Card', 40), ('Water', 50), ('Electricity', 60), ('Gas', 70),
    ('Cable', 80), ('Internet', 90), ('Phone', 100), ('Groceries', 110),
    ('Dining Out', 120), ('Transportation', 130), ('Insurance', 140),
    ('Healthcare', 150), ('Childcare', 160), ('Education', 170),
    ('Entertainment', 180), ('Subscriptions', 190), ('Savings', 200),
    ('Debt Payment', 210), ('Salary', 220), ('Other Income', 230), ('Other', 240)
) as defaults(name, sort_order)
on conflict (household_id, name) do nothing;

insert into public.categories (household_id, name)
select distinct household_id, category
from public.budget_entries
where length(btrim(category)) > 0
on conflict (household_id, name) do nothing;

alter table public.budget_entries add column if not exists category_id bigint;

update public.budget_entries e
set category_id = c.id
from public.categories c
where c.household_id = e.household_id and c.name = e.category and e.category_id is null;

alter table public.budget_entries alter column category_id set not null;
alter table public.budget_entries
    add constraint budget_entries_category_id_fkey
    foreign key (category_id) references public.categories(id);
create index if not exists budget_entries_category_id_idx on public.budget_entries(category_id);

alter table public.budget_entries drop constraint if exists budget_entries_category_not_blank;
alter table public.budget_entries drop column category;
