alter table public.accounts drop constraint accounts_household_id_key;

create index accounts_household_id_idx on public.accounts(household_id);

create table public.account_invitations (
    id bigint generated by default as identity primary key,
    household_id bigint not null references public.households(id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    used_at timestamptz,
    used_by_account_id bigint references public.accounts(id) on delete set null,
    created_at timestamptz not null default now()
);

create index account_invitations_household_id_idx on public.account_invitations(household_id);
create index account_invitations_expires_at_idx on public.account_invitations(expires_at);
alter table public.account_invitations enable row level security;

create or replace function public.redeem_household_invitation(
    p_token_hash text, p_username text, p_password_hash text
) returns bigint
language plpgsql security definer set search_path = public as $$
declare
    invitation public.account_invitations;
    new_account_id bigint;
begin
    select * into invitation from public.account_invitations
    where token_hash = p_token_hash and used_at is null and expires_at > now()
    for update;
    if not found then raise exception 'Invalid or expired invitation'; end if;

    insert into public.accounts (household_id, username, password_hash)
    values (invitation.household_id, p_username, p_password_hash)
    returning id into new_account_id;

    update public.account_invitations
    set used_at = now(), used_by_account_id = new_account_id
    where id = invitation.id;
    return new_account_id;
end;
$$;

revoke execute on function public.redeem_household_invitation(text, text, text)
from public, anon, authenticated;
grant execute on function public.redeem_household_invitation(text, text, text) to service_role;
