create table if not exists public.grocery_items (
    id bigint generated by default as identity primary key,
    household_id bigint not null references public.households(id) on delete cascade,
    added_by_account_id bigint not null references public.accounts(id) on delete restrict,
    item_name text not null check (length(btrim(item_name)) between 1 and 120),
    completed boolean not null default false,
    created_at timestamptz not null default now(),
    completed_at timestamptz
);

create index if not exists grocery_items_household_status_created_idx
    on public.grocery_items (household_id, completed, created_at desc);

alter table public.grocery_items enable row level security;
revoke all on public.grocery_items from anon, authenticated;

create or replace function public.set_grocery_item_completion(
    p_item_id bigint, p_household_id bigint, p_completed boolean
) returns boolean language plpgsql security definer set search_path = public as $$
begin
    update public.grocery_items
       set completed = p_completed,
           completed_at = case when p_completed then now() else null end
     where id = p_item_id and household_id = p_household_id;
    return found;
end;
$$;

revoke execute on function public.set_grocery_item_completion(bigint,bigint,boolean)
    from public, anon, authenticated;
grant execute on function public.set_grocery_item_completion(bigint,bigint,boolean)
    to service_role;
