alter table public.accounts
    add column role text not null default 'member' check (role in ('owner', 'member')),
    add column disabled_at timestamptz,
    add column password_changed_at timestamptz;

with owners as (
    select distinct on (household_id) id
    from public.accounts
    order by household_id, created_at, id
)
update public.accounts set role = 'owner' where id in (select id from owners);

create table public.security_audit_events (
    id bigint generated by default as identity primary key,
    account_id bigint references public.accounts(id) on delete set null,
    household_id bigint references public.households(id) on delete set null,
    event_type text not null,
    ip_hash text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index security_audit_events_account_created_idx on public.security_audit_events(account_id, created_at desc);
create index security_audit_events_household_created_idx on public.security_audit_events(household_id, created_at desc);
alter table public.security_audit_events enable row level security;

create table public.auth_rate_limits (
    key_hash text primary key,
    window_started_at timestamptz not null,
    attempts integer not null
);
alter table public.auth_rate_limits enable row level security;

create or replace function public.check_auth_rate_limit(
    p_key_hash text, p_limit integer, p_window_seconds integer
) returns boolean
language plpgsql security definer set search_path = public as $$
declare current_attempts integer;
begin
    insert into public.auth_rate_limits (key_hash, window_started_at, attempts)
    values (p_key_hash, now(), 1)
    on conflict (key_hash) do update set
        attempts = case
            when auth_rate_limits.window_started_at <= now() - make_interval(secs => p_window_seconds)
            then 1 else auth_rate_limits.attempts + 1 end,
        window_started_at = case
            when auth_rate_limits.window_started_at <= now() - make_interval(secs => p_window_seconds)
            then now() else auth_rate_limits.window_started_at end
    returning attempts into current_attempts;
    return current_attempts <= p_limit;
end;
$$;

revoke execute on function public.check_auth_rate_limit(text, integer, integer)
from public, anon, authenticated;
grant execute on function public.check_auth_rate_limit(text, integer, integer) to service_role;

revoke all on public.security_audit_events from anon, authenticated;
revoke all on public.auth_rate_limits from anon, authenticated;
